version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
  post_build:
    commands:
      - echo Build is completed on `date`
artifacts:
  files:
    - '**/*'
