version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      -
      - python HelloGianna.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloGianna.py
